"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from elasticsearch import Elasticsearch
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@%#05f-d656g#+pq)2$o-riz3y#cif(!ir%f3ms9ek^as5^+bm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'comptes.CustomUser'


# ==============================================================================
# INSTALLED APPLICATIONS CONFIGURATION
# ==============================================================================

DJANGO_APPS = [
    'daphne',  # Doit impérativement être avant django.contrib.staticfiles
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    # ---- REST Framework & API Docs ----
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'drf_spectacular',
    
    # ---- Authentication & OAuth ----
    'allauth',
    'allauth.account',
    'allauth.socialaccount', 
    'social_django',  
    'dj_rest_auth',  
    
    # ---- Asynchronous & Tasks ----
    'django_celery_beat',
    'corsheaders',
    
    # ---- Database & Search Utilities ----
    'mptt',
    'django_elasticsearch_dsl',
    'taggit',
    # 'modeltranslation',
]

LOCAL_APPS = [
    # ---- Core & System Apps ----
    'apps.accounts',         
    'apps.notifications',   
    'apps.coupons',
    'apps.favorites',
    'apps.payments', 
    
    # ---- Shared Domain Apps (Client & Vendor) ----
    'apps.shops',           
    'apps.products',        
    'apps.categories',      
    'apps.restaurant',      
    
    'apps.carts',           
    'apps.orders',          
    'apps.comments',        
    'apps.contacts',        
    'apps.chat',            
]

# Fusion finale requise par Django
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # Optionnel
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated',  # Par défaut, restreindre aux utilisateurs authentifiés
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    # Explicit default throttle classes (empty → no global throttling)
    'DEFAULT_THROTTLE_CLASSES': [],
    # Throttling rates for specific scopes used by view-level throttles
    'DEFAULT_THROTTLE_RATES': {
        # Application-specific scopes
        'otp': '3/hour',      # limit OTP requests (send/verify/reset) to 3 per hour per IP/user
        'login': '10/min',    # limit login/token obtain attempts
        # Safe defaults to avoid ImproperlyConfigured when built-in throttles are used
        'anon': '1000/day',   # anonymous requests fallback
        'user': '10000/day',  # authenticated user requests fallback
    }
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Ecommerce API',
    'DESCRIPTION': 'Documentation Swagger pour l\'API Ecommerce.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

SIMPLE_JWT = {
  # It will work instead of the default serializer(TokenObtainPairSerializer).
  "TOKEN_OBTAIN_SERIALIZER": "comptes.serializers.MyTokenObtainPairSerializer",
  "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
  "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
  "BLACKLIST_AFTER_ROTATION": True,
  # ...
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000"
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ELASTICSEARCH_DSL = {
#     'default': {
#         'hosts': 'https://elastic:KqKm=Xeh3f=rVSChk-L*@localhost:9200',
#         'http_auth': ('elastic', 'KqKm=Xeh3f=rVSChk-L*'),
#         'use_ssl': True,
#         'verify_certs': False  # car certificat auto-signé
#     },
# }
# ELASTICSEARCH_DSL = {
#     'default': {
#         'hosts': ['http://localhost:9200'],
#         # 'basic_auth': ('elastic', 'KqKm=Xeh3f=rVSChk-L*'),
#         # 'verify_certs': False,
#         # 'ssl_show_warn': False,
#     }
# }

ELASTICSEARCH_DSL = {
    'default': {
        'hosts': 'https://localhost:9200',
        'http_auth': ('elastic', 'VGauc4i1GZnwq6gIJXo6'),
        'verify_certs': False,
        'ssl_show_warn': False,
    }
}

ASGI_APPLICATION = 'ecommerce.asgi.application'
WSGI_APPLICATION = 'ecommerce.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Ecommerce',
        'USER': 'postgres',
        'PASSWORD': 'P@blo 2003',
        'HOST': '127.0.0.1',
        'PORT': 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/
# MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'

# LANGUAGES = [
#     ('fr', 'French'),
#     ('en', 'English'),
#     ('ar', 'Arabe'),
# ]

# LANGUAGE_CODE = 'en'  # langue par défaut
# USE_I18N = True
# USE_L10N = True
# USE_TZ = True

# MODELTRANSLATION_LANGUAGES = ('en', 'fr', 'ar')

LANGUAGE_CODE = 'fr' 

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Channels utilise un Layer de communication pour la gestion des messages, souvent Redis
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],  # L'URL de ton serveur Redis
        },
    },
}

# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels.layers.InMemoryChannelLayer',
#     },
# }

# Clés et secrets des fournisseurs OAuth
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '<votre-client-id-google>'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '<votre-client-secret-google>'

SOCIAL_AUTH_FACEBOOK_KEY = '<votre-app-id-facebook>'
SOCIAL_AUTH_FACEBOOK_SECRET = '<votre-app-secret-facebook>'
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']


# Spécifiez qu'il n'y a pas de champ username
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False

# Configurez l'authentification pour utiliser uniquement l'email
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # ou 'mandatory' selon vos besoins

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'pablogenius03@gmail.com'
EMAIL_HOST_PASSWORD = 'aniy ubrb yfik iltu'
DEFAULT_FROM_EMAIL = 'pablogenius03@gmail.com'

# aniy ubrb yfik iltu


# ============================================================================
# CELERY CONFIGURATION
# ============================================================================
# Broker Redis pour les tâches asynchrones
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes

# Celery Beat - Planification des tâches périodiques

CELERY_BEAT_SCHEDULE = {
    # Recalcul quotidien des stats à 2h du matin UTC
    'recalculate-daily-shop-statistics': {
        'task': 'boutique.tasks.recalculate_daily_shop_statistics',
        'schedule': crontab(hour=2, minute=0),  # 2 AM UTC
    },
    # (Optionnel) Nettoyage hebdomadaire des anciennes stats le dimanche à 3h
    'cleanup-old-statistics': {
        'task': 'boutique.tasks.cleanup_old_statistics',
        'schedule': crontab(day_of_week=0, hour=3, minute=0),  # Dimanche 3 AM
    },
    # Expiration des sponsorings produits (toutes les 10 minutes)
    'deactivate-expired-sponsored-products': {
        'task': 'produits.tasks.deactivate_expired_sponsored_products',
        'schedule': crontab(minute='*/10'),
    },
    # Expiration des promotions produits (toutes les 10 minutes)
    'deactivate-expired-promotions': {
        'task': 'produits.tasks.deactivate_expired_promotions',
        'schedule': crontab(minute='*/10'),
    },
    # Expiration des quotes (toutes les 10 minutes)
    'expire-quotes': {
        'task': 'produits.tasks.expire_quotes',
        'schedule': crontab(minute='*/10'),
    },
    # Purge quotidienne des comptes supprimes/inactifs
    'purge-deleted-accounts': {
        'task': 'comptes.tasks.purge_deleted_accounts_task',
        'schedule': crontab(hour=3, minute=30),
    },
    # Nettoyage periodique des OTP expires
    'cleanup-expired-otps': {
        'task': 'comptes.tasks.cleanup_expired_otps',
        'schedule': crontab(minute=15, hour='*/1'),
    },
}
